apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-tracker
resources:
  - ../kubernetes
  - namespace.yaml
  - storage-class.yaml
  - tunnel.yaml
  - network-policy.yaml
replicas:
  - name: arch-security-tracker
    count: 0
patches:
  - path: tracker.yaml
  - path: pvc.yaml
  - path: configmap.yaml
