apiVersion: v1
kind: ConfigMap
metadata:
  name: arch-security-tracker
data:
  TRACKER_PUBLIC_URL: https://security.archlinux.mx
  TRACKER_SECRET_KEY_FILE: /run/secrets/tracker/secret_key
  TRACKER_PROXY_HOPS: "0"
