on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:base
    env:
      TRACKER_CONFIG_LOCAL: 'false'
      PYTHONPATH: '.'
    steps:
      - name: Install Git
        run: pacman -Syu --needed --noconfirm git
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Arch dependencies
        run: pacman -Syu --needed --noconfirm $(cat dev/arch-packages)
      - name: Run tests
        run: |
          python -m compileall -q tracker test config.py
          pytest -q test
          isort --check-only --diff tracker test config.py
